// Users 
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTHENTICATING_USER = "AUTHENTICATING_USER";
export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCHING_RESTAURANTS = "FETCHING_RESTAURANTS";
export const FETCHED_RESTAURANTS = "FETCHED_RESTAURANTS";
export const UNFETCH_RESTAURANTS = "UNFETCH_RESTAURANTS";
export const ADD_REVIEW = "ADD_REVIEW";
export const SELECT_RESTAURANT = "SELECT_RESTAURANT";
export const DESELECT_RESTAURANT = "DESELECT_RESTAURANT";
